# Dependency Review configuration
# https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/configuring-dependency-review

# Fail the action on any security vulnerabilities
fail-on-severity: moderate

# Allow specific licenses
allow-licenses:
  - MIT
  - Apache-2.0
  - BSD-2-Clause
  - BSD-3-Clause
  - ISC
  - 0BSD
  - Unlicense

# Deny specific licenses that are problematic
deny-licenses:
  - GPL-2.0
  - GPL-3.0
  - AGPL-1.0
  - AGPL-3.0

# Allow specific packages even if they have denied licenses
allow-dependencies-licenses:
  - pkg:npm/some-gpl-package@1.0.0

# Comment configuration
comment-summary-in-pr: always