name: Code Quality

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  code-quality:
    name: Code Quality Checks
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: web-admin/package-lock.json

    - name: Install dependencies
      working-directory: ./web-admin
      run: npm ci

    - name: Run ESLint
      working-directory: ./web-admin
      run: npm run lint -- --format=json --output-file=eslint-report.json
      continue-on-error: true

    - name: Run TypeScript compiler
      working-directory: ./web-admin
      run: npm run type-check

    - name: Check code formatting
      working-directory: ./web-admin
      run: npx prettier --check "src/**/*.{ts,tsx,js,jsx,json,css,md}"

    - name: Upload ESLint report
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: eslint-report
        path: web-admin/eslint-report.json

  dependency-review:
    name: Dependency Review
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Dependency Review
      uses: actions/dependency-review-action@v3
      with:
        config-file: '.github/dependency-review-config.yml'